[theme]
base = "light"
primaryColor = "#1E3A78"
backgroundColor = "#F5F5F6"
secondaryBackgroundColor = "#FDFDFD"
textColor = "#242526"
font = "sans serif"

[server]
headless = true

[browser]
gatherUsageStats = false
